### ISSUE TITLE
Line across toolbar

### ISSUE THREAD

**Issue by cpritchett** [dracula/microsoft-edge#1]
After updating to the newest version of Edge on MacOS, there's a line across the toolbar.

Example:
<img width="312" alt="Screenshot 2023-08-26 at 11 18 04 AM" src="https://github.com/dracula/microsoft-edge/assets/3866278/e9ec524f-8b2f-4a49-88ba-78966b26ccce">

Version info:
<img width="347" alt="Screenshot 2023-08-26 at 11 17 48 AM" src="https://github.com/dracula/microsoft-edge/assets/3866278/79d70bab-a302-42d9-88d2-e8e357b214bd">

**Comment by hudsonm62** [comment]
Oh wow. This looks a lot of worse on Mac.

Lets continue this on the PR.
